"""initial tables

Revision ID: e6a12178d39b
Revises: 
Create Date: 2026-01-19 02:57:28.750487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a12178d39b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Create users table first (no dependencies)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # 2. Create lobbies table (depends on users, game_id FK added later)
    op.create_table('lobbies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=6), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'READY', 'STARTED', 'CANCELLED', name='lobbystatus'), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobbies_invite_code'), 'lobbies', ['invite_code'], unique=True)

    # 3. Create games table (depends on users and lobbies)
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'IN_PROGRESS', 'FINISHED', name='gamestatus'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('current_turn_player_id', sa.Integer(), nullable=False),
    sa.Column('turn_order_json', sa.Text(), nullable=False),
    sa.Column('board_json', sa.Text(), nullable=False),
    sa.Column('players_json', sa.Text(), nullable=False),
    sa.Column('available_tiles_json', sa.Text(), nullable=False),
    sa.Column('discarded_tiles_json', sa.Text(), nullable=False),
    sa.Column('last_action_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_turn_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 4. Add game_id FK to lobbies (circular dependency resolved)
    op.create_foreign_key('fk_lobbies_game_id', 'lobbies', 'games', ['game_id'], ['id'])

    # 5. Create game_actions table (depends on games and users)
    op.create_table('game_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # 6. Create lobby_players table (depends on lobbies and users)
    op.create_table('lobby_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.Enum('BLUE', 'RED', 'GREEN', 'YELLOW', name='playercolor'), nullable=False),
    sa.Column('turn_order', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lobby_players')
    op.drop_table('game_actions')
    op.drop_constraint('fk_lobbies_game_id', 'lobbies', type_='foreignkey')
    op.drop_table('games')
    op.drop_index(op.f('ix_lobbies_invite_code'), table_name='lobbies')
    op.drop_table('lobbies')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
